In [ ]:

# import pandas as pd

# # Create sample employee data
# data = {
#     'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
#     'Age': [25, 30, 35, 40, 28, 33, 29, 32, 27, 31],
#     'City': ['New York', 'Los Angeles', 'New York', 'San Francisco', 'Miami',
#              'Houston', 'Boston', 'New York', 'Chicago', 'Seattle'],
#     'Salary': [50000, 60000, 70000, 80000, 55000, 62000, 58000, 75000, 67000, 72000]
# }

# # Create a DataFrame
# df = pd.DataFrame(data)

# # Save to CSV file
# df.to_csv('employees.csv', index=False)

# print("employees.csv file created successfully!")

employees.csv file created successfully!

# 01 Clean Dataset of First_Health_Camp_Attended.csv

In [ ]:
import pandas as pd
# Load the employee data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/First_Health_Camp_Attended.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
# Display the shape of the DataFrame
print("\nShape of the DataFrame:")
print(df.shape)
# Display the columns of the DataFrame
print("\nColumns in the DataFrame:")
print(df.columns)

print(df.info())
print(df.describe())

#Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

#handle NnaN values
#Drop rows with any NaN values
df_cleaned = df.dropna(inplace=True)
print("\nData after dropping rows with NaN values:")
print(df_cleaned)
print(df.isnull().sum())

print("SUCCESSFULLY LOADED THE DATASET AND HANDLED MISSING VALUES!")

#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_health_camp_Attended_data.csv', index=False)
# print("Cleaned data exported  successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Patient_ID  Health_Camp_ID  Donation  Health_Score  Unnamed: 4
0      506181            6560        40      0.439024         NaN
1      494977            6560        20      0.097561         NaN
2      518680            6560        10      0.048780         NaN
3      509916            6560        30      0.634146         NaN
4      488006            6560        20      0.024390         NaN

Shape of the DataFrame:
(6218, 5)

Columns in the DataFrame:
Index(['Patient_ID', 'Health_Camp_ID', 'Donation', 'Health_Score',
       'Unnamed: 4'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6218 entries, 0 to 6217
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      6218 non-null   int64
 1   Health_Camp_ID  6218 non-null   int64
 2   Donation        6218 non-null   int64
 3   Health_Score    6218 non-null   float64
 4   Unnamed: 4      0 non-null      float64
dtypes: float64(2), int64(3)
memory usage: 243.0 KB
None
          Patient_ID  Health_Camp_ID     Donation  Health_Score  Unnamed: 4
count    6218.000000     6218.000000  6218.000000   6218.000000         0.0
mean   506929.053715     6552.904149    32.587649      0.517668         NaN
std     12437.711002       19.095027    24.501676      0.289211         NaN
min    485702.000000     6524.000000    10.000000      0.001667         NaN
25%    496069.000000     6538.000000    20.000000      0.263094         NaN
50%    506704.000000     6543.000000    30.000000      0.529706         NaN
75%    517747.750000     6570.000000    40.000000      0.771429         NaN
max    528657.000000     6587.000000   330.000000      1.000000         NaN

Missing values in each column:
Patient_ID           0
Health_Camp_ID       0
Donation             0
Health_Score         0
Unnamed: 4        6218
dtype: int64

Data after dropping rows with NaN values:
None
Patient_ID        0
Health_Camp_ID    0
Donation          0
Health_Score      0
Unnamed: 4        0
dtype: int64
SUCCESSFULLY LOADED THE DATASET AND HANDLED MISSING VALUES!
Cleaned data exported to 'cleaned_health_camp_data_Attended.csv' successfully!


# 02 Clean Dataset of Health_Camp_Detail.csv

In [ ]:
import pandas as pd
# Load the employee data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/Health_Camp_Detail.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

#Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nData is already clean, no NaN values found.")

#check for duplicate rows
print("\nChecking for duplicate rows:")
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

print("\nData after checking for duplicates:")
if duplicates > 0:
    df = df.drop_duplicates()
    print("Duplicates removed.")
else:
    print("No duplicates found.")

#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_health_camp_detail.csv', index=False)
# print("Cleaned data exported  successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Health_Camp_ID Camp_Start_Date Camp_End_Date Category1 Category2  Category3
0            6560       16-Aug-03     20-Aug-03     First         B          2
1            6530       16-Aug-03     28-Oct-03     First         C          2
2            6544       03-Nov-03     15-Nov-03     First         F          1
3            6585       22-Nov-03     05-Dec-03     First         E          2
4            6561       30-Nov-03     18-Dec-03     First         E          1

Shape of the DataFrame:
(65, 6)

Columns in the DataFrame:
Index(['Health_Camp_ID', 'Camp_Start_Date', 'Camp_End_Date', 'Category1',
       'Category2', 'Category3'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Health_Camp_ID   65 non-null     int64
 1   Camp_Start_Date  65 non-null     object
 2   Camp_End_Date    65 non-null     object
 3   Category1        65 non-null     object
 4   Category2        65 non-null     object
 5   Category3        65 non-null     int64
dtypes: int64(2), object(4)
memory usage: 3.2+ KB
None
       Health_Camp_ID  Category3
count        65.00000  65.000000
mean       6555.00000   1.953846
std          18.90767   0.211451
min        6523.00000   1.000000
25%        6539.00000   2.000000
50%        6555.00000   2.000000
75%        6571.00000   2.000000
max        6587.00000   2.000000

Missing values in each column:
Health_Camp_ID     0
Camp_Start_Date    0
Camp_End_Date      0
Category1          0
Category2          0
Category3          0
dtype: int64

Data is already clean, no NaN values found.

Checking for duplicate rows:
Number of duplicate rows: 0

Data after checking for duplicates:
No duplicates found.
Cleaned data exported to 'cleaned_health_camp_detail.csv' successfully!


# 03 Clean Dataset of Patient_Profile.csv

In [ ]:
import pandas as pd
# Load the employee data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/Patient_Profile.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

print("\nChecking for duplicate rows:")
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

Data loaded successfully!
First 5 rows of the dataset:
   Patient_ID  Online_Follower  LinkedIn_Shared  Twitter_Shared  \
0      516956                0                0               0
1      507733                0                0               0
2      508307                0                0               0
3      512612                0                0               0
4      521075                0                0               0

   Facebook_Shared  Income  Education_Score   Age First_Interaction City_Type  \
0                0     1.0             90.0  39.0         18-Jun-03       NaN
1                0     1.0              NaN  40.0         20-Jul-03         H
2                0     3.0             87.0  46.0         02-Nov-02         D
3                0     1.0             75.0  47.0         02-Nov-02         D
4                0     3.0              NaN  80.0         24-Nov-02         H

   Employer_Category
0  Software Industry
1  Software Industry
2               BFSI
3          Education
4             Others

Shape of the DataFrame:
(37633, 11)

Columns in the DataFrame:
Index(['Patient_ID', 'Online_Follower', 'LinkedIn_Shared', 'Twitter_Shared',
       'Facebook_Shared', 'Income', 'Education_Score', 'Age',
       'First_Interaction', 'City_Type', 'Employer_Category'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37633 entries, 0 to 37632
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         37633 non-null  int64
 1   Online_Follower    37633 non-null  int64
 2   LinkedIn_Shared    37633 non-null  int64
 3   Twitter_Shared     37633 non-null  int64
 4   Facebook_Shared    37633 non-null  int64
 5   Income             4362 non-null   float64
 6   Education_Score    1384 non-null   float64
 7   Age                5015 non-null   float64
 8   First_Interaction  37633 non-null  object
 9   City_Type          14249 non-null  object
 10  Employer_Category  2840 non-null   object
dtypes: float64(3), int64(5), object(3)
memory usage: 3.2+ MB
None
          Patient_ID  Online_Follower  LinkedIn_Shared  Twitter_Shared  \
count   37633.000000     37633.000000     37633.000000    37633.000000
mean   507148.408338         0.022533         0.027077        0.021603
std     12411.747993         0.148412         0.162311        0.145387
min    485678.000000         0.000000         0.000000        0.000000
25%    496393.000000         0.000000         0.000000        0.000000
50%    507104.000000         0.000000         0.000000        0.000000
75%    517882.000000         0.000000         0.000000        0.000000
max    528657.000000         1.000000         1.000000        1.000000

       Facebook_Shared       Income  Education_Score          Age
count     37633.000000  4362.000000      1384.000000  5015.000000
mean          0.023543     1.077717        78.231288    49.129811
std           0.151623     1.332109         8.751698    12.555632
min           0.000000     0.000000        45.000000    30.000000
25%           0.000000     0.000000        72.000000    40.000000
50%           0.000000     1.000000        79.000000    44.000000
75%           0.000000     2.000000        85.000000    52.000000
max           1.000000     6.000000       101.000000    80.000000

Missing values in each column:
Patient_ID               0
Online_Follower          0
LinkedIn_Shared          0
Twitter_Shared           0
Facebook_Shared          0
Income               33271
Education_Score      36249
Age                  32618
First_Interaction        0
City_Type            23384
Employer_Category    34793
dtype: int64
(37633, 11)

Checking for duplicate rows:
Number of duplicate rows: 0


# 04 Clean Dataset of Second_Health_Camp_Attended.csv

In [ ]:
import pandas as pd
# Load the employee data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/Second_Health_Camp_Attended.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

print("\nChecking for duplicate rows:")
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_Second_Health_Camp_Attended.csv', index=False)
# print("Cleaned data exported  successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Patient_ID  Health_Camp_ID  Health Score
0      526631            6536      0.875136
1      509122            6536      0.755700
2      498864            6536      0.673181
3      515398            6536      0.722041
4      504624            6536      0.464712

Shape of the DataFrame:
(7819, 3)

Columns in the DataFrame:
Index(['Patient_ID', 'Health_Camp_ID', 'Health Score'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7819 entries, 0 to 7818
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      7819 non-null   int64
 1   Health_Camp_ID  7819 non-null   int64
 2   Health Score    7819 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 183.4 KB
None
          Patient_ID  Health_Camp_ID  Health Score
count    7819.000000     7819.000000   7819.000000
mean   507184.188004     6534.044891      0.554178
std     12358.248560        9.135749      0.249378
min    485682.000000     6523.000000      0.058993
25%    496537.500000     6529.000000      0.389626
50%    507078.000000     6534.000000      0.518797
75%    517805.500000     6536.000000      0.762724
max    528657.000000     6555.000000      1.000000

Missing values in each column:
Patient_ID        0
Health_Camp_ID    0
Health Score      0
dtype: int64
(7819, 3)

Checking for duplicate rows:
Number of duplicate rows: 0
Cleaned data exported to 'cleaned_health_camp_detail.csv' successfully!


# 05 Clean Dataset of Third_Health_Camp_Attended.csv

In [ ]:
import pandas as pd
# Load the employee data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/Third_Health_Camp_Attended.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

print("\nChecking for duplicate rows:")
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_Third_Health_Camp_Attended.csv', index=False)
# print("Cleaned data exported successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Patient_ID  Health_Camp_ID  Number_of_stall_visited  \
0      517875            6527                        3
1      504692            6578                        1
2      504692            6527                        3
3      493167            6527                        4
4      510954            6528                        2

   Last_Stall_Visited_Number
0                          1
1                          1
2                          1
3                          4
4                          2

Shape of the DataFrame:
(6515, 4)

Columns in the DataFrame:
Index(['Patient_ID', 'Health_Camp_ID', 'Number_of_stall_visited',
       'Last_Stall_Visited_Number'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6515 entries, 0 to 6514
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient_ID                 6515 non-null   int64
 1   Health_Camp_ID             6515 non-null   int64
 2   Number_of_stall_visited    6515 non-null   int64
 3   Last_Stall_Visited_Number  6515 non-null   int64
dtypes: int64(4)
memory usage: 203.7 KB
None
          Patient_ID  Health_Camp_ID  Number_of_stall_visited  \
count    6515.000000     6515.000000              6515.000000
mean   506982.062011     6543.653415                 2.923254
std     12489.080729       22.105649                 1.688500
min    485679.000000     6527.000000                 0.000000
25%    496100.000000     6527.000000                 1.000000
50%    506825.000000     6528.000000                 3.000000
75%    517793.500000     6578.000000                 4.000000
max    528656.000000     6578.000000                 7.000000

       Last_Stall_Visited_Number
count                6515.000000
mean                    2.404144
std                     1.469623
min                     0.000000
25%                     1.000000
50%                     2.000000
75%                     3.000000
max                     7.000000

Missing values in each column:
Patient_ID                   0
Health_Camp_ID               0
Number_of_stall_visited      0
Last_Stall_Visited_Number    0
dtype: int64
(6515, 4)

Checking for duplicate rows:
Number of duplicate rows: 0
Cleaned data exported to 'cleaned_health_camp_detail.csv' successfully!


# 06 Clean Dataset of Train.csv

In [ ]:
import pandas as pd
# Load the  data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/Train.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

print("\nChecking for duplicate rows:")
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

#Drop rows with empty values
df.dropna(inplace=True)
print("\nData after dropping rows with NaN values:")
print(df.isnull().sum())
print(df.shape)

#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_Train.csv', index=False)
# print("Cleaned data exported successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5
0      489652            6578         10-Sep-05     4     0     0     0     2
1      507246            6578         18-Aug-05    45     5     0     0     7
2      523729            6534         29-Apr-06     0     0     0     0     0
3      524931            6535         07-Feb-04     0     0     0     0     0
4      521364            6529         28-Feb-06    15     1     0     0     7

Shape of the DataFrame:
(75278, 8)

Columns in the DataFrame:
Index(['Patient_ID', 'Health_Camp_ID', 'Registration_Date', 'Var1', 'Var2',
       'Var3', 'Var4', 'Var5'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75278 entries, 0 to 75277
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         75278 non-null  int64
 1   Health_Camp_ID     75278 non-null  int64
 2   Registration_Date  74944 non-null  object
 3   Var1               75278 non-null  int64
 4   Var2               75278 non-null  int64
 5   Var3               75278 non-null  int64
 6   Var4               75278 non-null  int64
 7   Var5               75278 non-null  int64
dtypes: int64(7), object(1)
memory usage: 4.6+ MB
None
          Patient_ID  Health_Camp_ID          Var1          Var2  \
count   75278.000000    75278.000000  75278.000000  75278.000000
mean   507233.325660     6547.597319      0.796156      0.238556
std     12404.734886       19.272983      7.626687      3.769594
min    485679.000000     6523.000000      0.000000      0.000000
25%    496505.250000     6534.000000      0.000000      0.000000
50%    507276.500000     6541.000000      0.000000      0.000000
75%    517919.000000     6562.000000      0.000000      0.000000
max    528657.000000     6587.000000    288.000000    156.000000

               Var3          Var4          Var5
count  75278.000000  75278.000000  75278.000000
mean       0.000385      0.022424      0.248386
std        0.019624      0.199570      1.213938
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000
max        1.000000      4.000000     31.000000

Missing values in each column:
Patient_ID             0
Health_Camp_ID         0
Registration_Date    334
Var1                   0
Var2                   0
Var3                   0
Var4                   0
Var5                   0
dtype: int64
(75278, 8)

Checking for duplicate rows:
Number of duplicate rows: 0

Data after dropping rows with NaN values:
Patient_ID           0
Health_Camp_ID       0
Registration_Date    0
Var1                 0
Var2                 0
Var3                 0
Var4                 0
Var5                 0
dtype: int64
(74944, 8)
Cleaned data exported successfully!


# 07 Clean Dataset of test.csv

In [ ]:
import pandas as pd
# Load the  data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Health_Care_Dataset/test.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

print("\nChecking for duplicate rows:")
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")


#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_test.csv', index=False)
# print("Cleaned data exported successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5
0      505701            6548         21-May-06     1     0     0     0     2
1      500633            6584         02-Jun-06     0     0     0     0     0
2      506945            6582         10-Aug-06     0     0     0     0     0
3      497447            6551         27-Aug-06     0     0     0     0     0
4      496446            6533         19-Sep-06     0     0     0     0     0

Shape of the DataFrame:
(35249, 8)

Columns in the DataFrame:
Index(['Patient_ID', 'Health_Camp_ID', 'Registration_Date', 'Var1', 'Var2',
       'Var3', 'Var4', 'Var5'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35249 entries, 0 to 35248
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         35249 non-null  int64
 1   Health_Camp_ID     35249 non-null  int64
 2   Registration_Date  35249 non-null  object
 3   Var1               35249 non-null  int64
 4   Var2               35249 non-null  int64
 5   Var3               35249 non-null  int64
 6   Var4               35249 non-null  int64
 7   Var5               35249 non-null  int64
dtypes: int64(7), object(1)
memory usage: 2.2+ MB
None
          Patient_ID  Health_Camp_ID          Var1          Var2  \
count   35249.000000    35249.000000  35249.000000  35249.000000
mean   507020.926863     6568.160373      0.819201      0.253312
std     12478.669016       13.212263      8.298817      3.984690
min    485678.000000     6525.000000      0.000000      0.000000
25%    496203.000000     6556.000000      0.000000      0.000000
50%    507018.000000     6568.000000      0.000000      0.000000
75%    517869.000000     6582.000000      0.000000      0.000000
max    528657.000000     6584.000000    344.000000    181.000000

               Var3          Var4          Var5
count  35249.000000  35249.000000  35249.000000
mean       0.000567      0.041845      0.258163
std        0.023814      0.268826      1.311230
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000
max        1.000000      8.000000     34.000000

Missing values in each column:
Patient_ID           0
Health_Camp_ID       0
Registration_Date    0
Var1                 0
Var2                 0
Var3                 0
Var4                 0
Var5                 0
dtype: int64
(35249, 8)

Checking for duplicate rows:
Number of duplicate rows: 0
Cleaned data exported successfully!


# 08 Clean Dataset of trending.csv

In [4]:
import pandas as pd
# Load the  data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Trending/trending.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

# print("\nChecking for duplicate rows:")
# duplicates = df.duplicated().sum()
# print(f"Number of duplicate rows: {duplicates}")


#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_test.csv', index=False)
# print("Cleaned data exported successfully!")

Data loaded successfully!
First 5 rows of the dataset:
   Unnamed: 0      id            original_title original_language  \
0           0  638974          Murder Mystery 2           English
1           1  677179                 Creed III           English
2           2  726759                    Tetris           English
3           3   76600  Avatar: The Way of Water           English
4           4  849869                       길복순            Korean

  release_date  popularity  vote_average  vote_count media_type  adult
0   2023-03-26     235.901         6.800         187      movie  False
1   2023-03-01    1537.879         7.200         561      movie  False
2   2023-03-15      66.661         7.700         100      movie  False
3   2022-12-14   10224.280         7.742        6335      movie  False
4   2023-02-17      33.985         6.900          39      movie  False

Shape of the DataFrame:
(16080, 10)

Columns in the DataFrame:
Index(['Unnamed: 0', 'id', 'original_title', 'original_language',
       'release_date', 'popularity', 'vote_average', 'vote_count',
       'media_type', 'adult'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16080 entries, 0 to 16079
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         16080 non-null  int64
 1   id                 16080 non-null  int64
 2   original_title     12060 non-null  object
 3   original_language  16080 non-null  object
 4   release_date       12060 non-null  object
 5   popularity         16080 non-null  float64
 6   vote_average       16080 non-null  float64
 7   vote_count         16080 non-null  int64
 8   media_type         16080 non-null  object
 9   adult              16080 non-null  bool
dtypes: bool(1), float64(2), int64(3), object(4)
memory usage: 1.1+ MB
None
       Unnamed: 0            id    popularity  vote_average   vote_count
count  16080.0000  1.608000e+04  16080.000000  16080.000000  16080.00000
mean    8039.5000  5.758387e+05    934.262000      7.536350   1039.75000
std     4642.0405  3.271352e+05   2229.935599      1.057306   2326.96193
min        0.0000  7.660000e+04     30.374000      4.800000      3.00000
25%     4019.7500  1.963872e+05     61.750250      6.875000      9.75000
50%     8039.5000  6.580765e+05     94.859000      7.721000     53.50000
75%    12059.2500  8.569955e+05    804.053750      8.040250    363.00000
max    16079.0000  1.049638e+06  10224.280000     10.000000   8697.00000

Missing values in each column:
Unnamed: 0              0
id                      0
original_title       4020
original_language       0
release_date         4020
popularity              0
vote_average            0
vote_count              0
media_type              0
adult                   0
dtype: int64
(16080, 10)


# 09 Clean Dataset of _output_All_Finance__Accounting_p1_p626.csv

In [5]:
import pandas as pd
# Load the  data from the CSV file from the provided GitHub URL
df = pd.read_csv('https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/Udmey%20Data/udemy_output_All_Finance__Accounting_p1_p626.csv')
print("Data loaded successfully!")

print("First 5 rows of the dataset:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumns in the DataFrame:")
print(df.columns)
print(df.info())
print(df.describe())

print("\nMissing values in each column:")
print(df.isnull().sum())
print(df.shape)

# print("\nChecking for duplicate rows:")
# duplicates = df.duplicated().sum()
# print(f"Number of duplicate rows: {duplicates}")


#Export the cleaned DataFrame to a new CSV file
# df.to_csv('F:\PROGRAMMING\MY PROJECTS\Datasets\Health_Care_Dataset\Cleaned_Data\cleaned_test.csv', index=False)
# print("Cleaned data exported successfully!")

Data loaded successfully!
First 5 rows of the dataset:
        id                                              title  \
0   762616  The Complete SQL Bootcamp 2020: Go from Zero t...
1   937678  Tableau 2020 A-Z: Hands-On Tableau Training fo...
2  1361790             PMP Exam Prep Seminar -  PMBOK Guide 6
3   648826         The Complete Financial Analyst Course 2020
4   637930  An Entire MBA in 1 Course:Award Winning Busine...

                                                 url  is_paid  \
0                 /course/the-complete-sql-bootcamp/     True
1                                 /course/tableau10/     True
2                        /course/pmp-pmbok6-35-pdus/     True
3     /course/the-complete-financial-analyst-course/     True
4  /course/an-entire-mba-in-1-courseaward-winning...     True

   num_subscribers  avg_rating  avg_rating_recent   rating  num_reviews  \
0           295509     4.66019            4.67874  4.67874        78006
1           209070     4.58956            4.60015  4.60015        54581
2           155282     4.59491            4.59326  4.59326        52653
3           245860     4.54407            4.53772  4.53772        46447
4           374836     4.47080            4.47173  4.47173        41630

   is_wishlisted  num_published_lectures  num_published_practice_tests  \
0          False                      84                             0
1          False                      78                             0
2          False                     292                             2
3          False                     338                             0
4          False                      83                             0

                created        published_time  discount_price__amount  \
0  2016-02-14T22:57:48Z  2016-04-06T05:16:11Z                   455.0
1  2016-08-22T12:10:18Z  2016-08-23T16:59:49Z                   455.0
2  2017-09-26T16:32:48Z  2017-11-14T23:58:14Z                   455.0
3  2015-10-23T13:34:35Z  2016-01-21T01:38:48Z                   455.0
4  2015-10-12T06:39:46Z  2016-01-11T21:39:33Z                   455.0

  discount_price__currency discount_price__price_string  price_detail__amount  \
0                      INR                         ₹455                8640.0
1                      INR                         ₹455                8640.0
2                      INR                         ₹455                8640.0
3                      INR                         ₹455                8640.0
4                      INR                         ₹455                8640.0

  price_detail__currency price_detail__price_string
0                    INR                     ₹8,640
1                    INR                     ₹8,640
2                    INR                     ₹8,640
3                    INR                     ₹8,640
4                    INR                     ₹8,640

Shape of the DataFrame:
(13608, 20)

Columns in the DataFrame:
Index(['id', 'title', 'url', 'is_paid', 'num_subscribers', 'avg_rating',
       'avg_rating_recent', 'rating', 'num_reviews', 'is_wishlisted',
       'num_published_lectures', 'num_published_practice_tests', 'created',
       'published_time', 'discount_price__amount', 'discount_price__currency',
       'discount_price__price_string', 'price_detail__amount',
       'price_detail__currency', 'price_detail__price_string'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13608 entries, 0 to 13607
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            13608 non-null  int64
 1   title                         13608 non-null  object
 2   url                           13608 non-null  object
 3   is_paid                       13608 non-null  bool
 4   num_subscribers               13608 non-null  int64
 5   avg_rating                    13608 non-null  float64
 6   avg_rating_recent             13608 non-null  float64
 7   rating                        13608 non-null  float64
 8   num_reviews                   13608 non-null  int64
 9   is_wishlisted                 13608 non-null  bool
 10  num_published_lectures        13608 non-null  int64
 11  num_published_practice_tests  13608 non-null  int64
 12  created                       13608 non-null  object
 13  published_time                13608 non-null  object
 14  discount_price__amount        12205 non-null  float64
 15  discount_price__currency      12205 non-null  object
 16  discount_price__price_string  12205 non-null  object
 17  price_detail__amount          13111 non-null  float64
 18  price_detail__currency        13111 non-null  object
 19  price_detail__price_string    13111 non-null  object
dtypes: bool(2), float64(5), int64(5), object(8)
memory usage: 1.9+ MB
None
                 id  num_subscribers    avg_rating  avg_rating_recent  \
count  1.360800e+04     13608.000000  13608.000000       13608.000000
mean   1.681721e+06      2847.010435      3.923293           3.912242
std    9.539271e+05      9437.865634      1.031304           1.039237
min    2.762000e+03         0.000000      0.000000           0.000000
25%    8.580862e+05        62.000000      3.800000           3.787315
50%    1.623421e+06       533.000000      4.194440           4.181735
75%    2.503720e+06      2279.500000      4.450000           4.452105
max    3.486006e+06    374836.000000      5.000000           5.000000

             rating   num_reviews  num_published_lectures  \
count  13608.000000  13608.000000            13608.000000
mean       3.912242    243.169827               32.224794
std        1.039237   1580.965895               42.766911
min        0.000000      0.000000                0.000000
25%        3.787315      7.000000               12.000000
50%        4.181735     24.000000               21.000000
75%        4.452105     87.000000               37.000000
max        5.000000  78006.000000              699.000000

       num_published_practice_tests  discount_price__amount  \
count                  13608.000000            12205.000000
mean                       0.110523              493.943794
std                        0.623501              267.827260
min                        0.000000              455.000000
25%                        0.000000              455.000000
50%                        0.000000              455.000000
75%                        0.000000              455.000000
max                        6.000000             3200.000000

       price_detail__amount
count          13111.000000
mean            4646.992602
std             3109.101019
min             1280.000000
25%             1600.000000
50%             3200.000000
75%             8640.000000
max            12800.000000

Missing values in each column:
id                                 0
title                              0
url                                0
is_paid                            0
num_subscribers                    0
avg_rating                         0
avg_rating_recent                  0
rating                             0
num_reviews                        0
is_wishlisted                      0
num_published_lectures             0
num_published_practice_tests       0
created                            0
published_time                     0
discount_price__amount          1403
discount_price__currency        1403
discount_price__price_string    1403
price_detail__amount             497
price_detail__currency           497
price_detail__price_string       497
dtype: int64
(13608, 20)